USE PROJECT;

--DATA ANALYSIS:-

--Q1. Which channel is most frequently used for transactions?
SELECT STORE_TYPE,
COUNT(CUST_ID) AS COUNT_ORDER
FROM TRANSACTIONS
GROUP BY STORE_TYPE
ORDER BY COUNT(CUST_ID) DESC;
-- e-Shop is the most frequently used.


--Q2. What is the count of male and female customers in the database?
SELECT GENDER,
COUNT(CUSTOMER_ID) AS TOTAL
FROM CUSTOMER
GROUP BY GENDER;

--Q3. From which city do we have the maximum number of customers and how many?
SELECT CITY_CODE,
COUNT(CUSTOMER_ID) AS TOTAL
FROM CUSTOMER
GROUP BY CITY_CODE
ORDER BY CITY_CODE DESC;
--City_code 10 has maximum number of customers i.e, 558.

--Q4. How many sub categories are there under the Books Category?
SELECT PROD_CAT,
COUNT(PROD_CAT_CODE) AS TOTAL
FROM PROD_CAT_INFO
GROUP BY PROD_CAT;
--There are 6 sub categories under the Books category.

--Q5. What is the maximum quantity of the products ever ordered?
SELECT MAX(QTY) AS [MAX QUANTITY ORDERED]
FROM TRANSACTIONS;

--Q6. What is the net total revenue generated in categories Electronics and Books?
SELECT PROD_CAT_CODE,
SUM(TOTAL_AMT) AS [TOTAL REVENUE GENERATED]
FROM TRANSACTIONS
GROUP BY PROD_CAT_CODE
HAVING PROD_CAT_CODE IN (3,5);

--Q7. How many customers have >10 transactions with us, excluding returns?
SELECT CUST_ID,
COUNT(TRANSACTION_ID) AS COUNTS
FROM TRANSACTIONS
GROUP BY CUST_ID
HAVING COUNT(TRANSACTION_ID) > 10
ORDER BY COUNTS ASC;

--Q8. What is the combined revenue earned from the "Electronics" and "Clothing" categories from "Flagship Stores"?
SELECT PROD_CAT_CODE, STORE_TYPE,
SUM(TOTAL_AMT) AS [TOTAL REVENUE GENERATED]
FROM TRANSACTIONS
GROUP BY PROD_CAT_CODE, STORE_TYPE
HAVING PROD_CAT_CODE IN (3,1) AND STORE_TYPE = 'FLAGSHIP STORE';

--Q9. What is the total revenue generated from "Males" customers in "Electronics" category? 
--Output should display total revenue by prod sub cat.
SELECT PROD_CAT_CODE,
SUM(TOTAL_AMT) AS TOT_REVENUE
FROM TRANSACTIONS AS T1
INNER JOIN CUSTOMER AS T2
ON T1.CUST_ID = T2.CUSTOMER_ID
WHERE GENDER = 'M' AND PROD_CAT_CODE = 3
GROUP BY PROD_CAT_CODE;

/*Q10. What is the % of sales and returns by product sub category; 
display only top 5 sub categories in terms of sales.*/
SELECT PROD_SUBCAT_CODE,
SUM(TOTAL_AMT)/
SUM(TAX) AS PER_SALES_RETURN FROM TRANSACTIONS 
GROUP BY PROD_SUBCAT_CODE
ORDER BY PROD_SUBCAT_CODE;

SELECT TOP 5* FROM TRANSACTIONS AS T1
INNER JOIN PROD_CAT_INFO AS T2
ON T1.prod_subcat_code = T2.prod_sub_cat_code
ORDER BY TOTAL_AMT DESC;

/*Q11. For all customers aged between 25 to 35 years find what is the net total revenue
generated by these customers in the last 30 days of the transactions from max transaction date
available in the data?*/
SELECT T1.CUST_ID, T1.TRAN_DATE,
DATEDIFF(YEAR, DOB, GETDATE()) AS YEARS,
SUM(TOTAL_AMT) AS NET_REVENUE
FROM TRANSACTIONS AS T1
INNER JOIN CUSTOMER AS T2
ON T1.CUST_ID = T2.CUSTOMER_ID
WHERE DATEDIFF(YEAR, DOB, GETDATE()) BETWEEN 25 AND 35
GROUP BY T1.CUST_ID, DATEDIFF(YEAR, DOB, GETDATE()), T1.TRAN_DATE
HAVING TRAN_DATE BETWEEN '2014-01-28' AND '2014-02-28'
ORDER BY T1.TRAN_DATE;

--Q12. Which product category has seen the max value of returns in the last 3 months of transactions?
SELECT TOP 1*
FROM TRANSACTIONS AS T1
INNER JOIN PROD_CAT_INFO AS T2
ON T1.PROD_CAT_CODE = T2.PROD_CAT_CODE
WHERE T1.TRAN_DATE BETWEEN '2013-11-28' AND '2014-02-28'
ORDER BY T1.QTY ASC;

--Q13. Which store type sells the maximum products; by value of sales amount and by quantity sold?
SELECT STORE_TYPE,
SUM(TOTAL_AMT) AS SALES_AMOUNT,
COUNT(CUST_ID) AS COUNTS
FROM TRANSACTIONS
GROUP BY STORE_TYPE
ORDER BY SUM(TOTAL_AMT) DESC;

--Q14. What are the categories for which average revenue is above the overall average?
SELECT T1.PROD_CAT_CODE, T1.TOTAL_AMT, T2.PROD_CAT
FROM TRANSACTIONS AS T1
INNER JOIN PROD_CAT_INFO AS T2
ON T1.prod_cat_code = T2.prod_cat_code
WHERE TOTAL_AMT >(SELECT AVG(TOTAL_AMT)
FROM TRANSACTIONS)
GROUP BY T1.PROD_CAT_CODE, T1.TOTAL_AMT, T2.PROD_CAT
ORDER BY T1.PROD_CAT_CODE;

/*Q15. Find the average and total revenue by each subcategory for the categories which are among top 5
categories in terms of quantity sold*/
SELECT TOP 5 PROD_SUBCAT_CODE,
AVG(TOTAL_AMT) AS AVG_REVENUE,
SUM(TOTAL_AMT) AS TOT_REVENUE,
COUNT(CUST_ID) AS COUNTS
FROM TRANSACTIONS
GROUP BY PROD_SUBCAT_CODE
ORDER BY COUNT(CUST_ID) DESC;




